services:
  config-service:
    image: ${DOCKERHUB_USERNAME}/config-service:latest
    restart: always
    ports:
      - "8888:8888"

  registry-service:
    image: ${DOCKERHUB_USERNAME}/registry-service:latest
    restart: always
    ports:
      - "8761:8761"
    depends_on:
      - config-service

  messagebroker-service:
    image: rabbitmq:3-management
    container_name: messagebroker-service
    restart: always
    ports:
      - "5672:5672"    # port AMQP pour la communication entre services
      - "15672:15672"  # interface web de management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}


  auth-service:
    image: ${DOCKERHUB_USERNAME}/auth-service:latest
    restart: always
    environment:
      - DATABASE_URL=${DB_URL_AUTH}
    ports:
      - "8081:8081"
    depends_on:
      - config-service
      - registry-service
      - messagebroker-service

  user-service:
    image: ${DOCKERHUB_USERNAME}/user-service:latest
    restart: always
    environment:
      - DATABASE_URL=${DB_URL_USER}
    ports:
      - "8082:8082"
    depends_on:
      - config-service
      - registry-service
      - messagebroker-service

  commentary-service:
    image: ${DOCKERHUB_USERNAME}/commentary-service:latest
    restart: always
    environment:
      - DATABASE_URL=${DB_URL_COMMENTARY}
    ports:
      - "8083:8083"
    depends_on:
      - config-service
      - registry-service
      - messagebroker-service

  publication-service:
    image: ${DOCKERHUB_USERNAME}/publication-service:latest
    restart: always
    environment:
      - DATABASE_URL=${DB_URL_PUBLICATION}
    ports:
      - "8085:8085"
    depends_on:
      - config-service
      - registry-service

  payment-service:
    image: ${DOCKERHUB_USERNAME}/payment-service:latest
    restart: always
    environment:
      - DATABASE_URL=${DB_URL_PAYMENT}
    ports:
      - "8086:8086"
    depends_on:
      - config-service
      - registry-service

  identity-service:
    image: ${DOCKERHUB_USERNAME}/identity-verification-service:latest
    restart: always
    environment:
      - DATABASE_URL=${DB_URL_IDENTITY}
    ports:
      - "8087:8087"
    depends_on:
      - config-service
      - registry-service

  proxy-service:
    image: ${DOCKERHUB_USERNAME}/proxy-service:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - config-service
      - registry-service
      - auth-service
      - user-service
      - commentary-service
      - publication-service
      - payment-service
      - identity-service
