version: "3.9"

networks:
  traefik-net:
    driver: bridge

services:
  config-service:
    image: ${DOCKERHUB_USERNAME}/config-service:latest
    restart: always
    ports:
      - "8888:8888"
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: 128M
        reservations:
          cpus: "0.10"
          memory: 64M

  registry-service:
    image: ${DOCKERHUB_USERNAME}/registry-service:latest
    restart: always
    ports:
      - "8761:8761"
    depends_on:
      - config-service
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: 128M
        reservations:
          cpus: "0.10"
          memory: 64M

  messagebroker-service:
    image: rabbitmq:3-management
    container_name: messagebroker-service
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: 256M
        reservations:
          cpus: "0.20"
          memory: 128M

  auth-service:
    image: ${DOCKERHUB_USERNAME}/auth-service:latest
    restart: always
    ports:
      - "8081:8001"
    environment:
      - DATABASE_URL=${DB_URL_AUTH}
      - INSTANCE_HOST=172.31.47.28
      - APP_PORT=8081
      - EUREKA_URL=http://ec2-16-171-142-15.eu-north-1.compute.amazonaws.com:8761/eureka
      - RABBITMQ_HOST=ec2-16-171-142-15.eu-north-1.compute.amazonaws.com
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - CONFIG_SERVER_URL=http://ec2-16-171-142-15.eu-north-1.compute.amazonaws.com:8888
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: 256M
        reservations:
          cpus: "0.10"
          memory: 64M

  user-service:
    image: ${DOCKERHUB_USERNAME}/user-service:latest
    restart: always
    ports:
      - "8082:8000"
    environment:
      - HOST_IP=172.31.47.28
      - APP_PORT=8082
      - EUREKA_URL=http://ec2-16-171-142-15.eu-north-1.compute.amazonaws.com:8761/eureka
      - CONFIG_SERVER_URL=http://ec2-16-171-142-15.eu-north-1.compute.amazonaws.com:8888
      - APP_NAME=users
      - PROFILE=default
      - MYSQL_DATABASE=user_db
      - MYSQL_USER=user_user
      - MYSQL_PASSWORD=ebate124
      - MYSQL_HOST=dreamhouse237-db.cbc4i248y7jv.eu-north-1.rds.amazonaws.com
      - MYSQL_PORT=3306
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@ec2-16-171-142-15.eu-north-1.compute.amazonaws.com:5672/%2f
      - START_RABBITMQ_CONSUMER=true
      - FRONTEND_BASE_URL=https://dreamhouse237.onrender.com
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: 256M
        reservations:
          cpus: "0.10"
          memory: 128M

  commentary-service:
    image: ${DOCKERHUB_USERNAME}/commentary-service:latest
    restart: always
    ports:
      - "8083:3003"
    environment:
      - DATABASE_URL=mysql://commentary_user:nflorinda124@dreamhouse237-db.cbc4i248y7jv.eu-north-1.rds.amazonaws.com:3306/commentary_db
      - HOST_IP=172.31.47.28
      - APP_PORT=8083
      - EUREKA_URL=http://ec2-16-171-142-15.eu-north-1.compute.amazonaws.com:8761/eureka
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@ec2-16-171-142-15.eu-north-1.compute.amazonaws.com:5672/%2f
      - PORT=3003
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: 128M
        reservations:
          cpus: "0.10"
          memory: 128M

  publication-service:
    image: ${DOCKERHUB_USERNAME}/publication-service:latest
    restart: always
    environment:
      - DATABASE_URL=${DB_URL_PUBLICATION}
    ports:
      - "8085:8085"
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: 128M
        reservations:
          cpus: "0.10"
          memory: 64M

  payment-service:
    image: ${DOCKERHUB_USERNAME}/payment-service:latest
    restart: always
    environment:
      - DATABASE_URL=${DB_URL_PAYMENT}
    ports:
      - "8086:8086"
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: 128M
        reservations:
          cpus: "0.10"
          memory: 64M

  identity-service:
    image: ${DOCKERHUB_USERNAME}/identity-verification-service:latest
    restart: always
    environment:
      - DATABASE_URL=${DB_URL_IDENTITY}
    ports:
      - "8087:8087"
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: 128M
        reservations:
          cpus: "0.10"
          memory: 64M

  proxy-service:
    image: ${DOCKERHUB_USERNAME}/proxy-service:latest
    restart: always
    networks:
      - traefik-net
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: 256M

  traefik:
    image: traefik:v3.3
    restart: always
    networks:
      - traefik-net
    ports:
      - "80:80"
      - "443:443"
    command:
      - "--log.level=INFO"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=htchamba124@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--providers.file.filename=/etc/traefik/dynamic.yml"
      - "--providers.file.watch=true"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "./traefik-dynamic.yml:/etc/traefik/dynamic.yml:ro"
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: 128M