http:
  routers:
    proxy:
      rule: "Host(`ec2-16-171-110-76.eu-north-1.compute.amazonaws.com`)"
      entryPoints:
        - websecure
      tls:
        certResolver: myresolver
      service: proxy-service

  services:
    proxy-service:
      loadBalancer:
        servers:
          - url: "http://proxy-service:8080"